swagger: "2.0"
info:
  title: Example API
  version: 1.0.0
host: jsonplaceholder.typicode.com 
schemes:
  - https
  - http
paths:
  /user:
    get:
      summary: get login Hotel data
      description: this is Hotel login data
      responses:
        200:
        description: Success
  /posts:
    get:
      description: Returns a list of users
      responses:
        200:
          description: List of users
          schema:
            type: array
            items:
              type: object
              properties:
                userId:
                  type: integer
                  format: int64
                id:
                  type: integer
                  format: int64
                title:
                  type: string
                body:
                  type: string